@host= https://localhost:7052

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Sven",
  "lastName": "Imholz",
  "email": "svenimholz@icloud.com",
  "password": "Test1234!"
}
