@host=https://localhost:7052
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTZXQuRG9tYWluLlBsYXllckFnZ3JlZ2F0ZS5WYWx1ZU9iamVjdHMuUGxheWVySWQiLCJnaXZlbl9uYW1lIjoiU3ZlbiIsImZhbWlseV9uYW1lIjoiSW1ob2x6IiwianRpIjoiMjllYjA2OTUtNjAxOS00ZjQyLWEyZGEtNTg4YjU2OTFmYTczIiwiZXhwIjoxNzE3MzI1MDU3LCJpc3MiOiJTdmVuSW1ob2x6IiwiYXVkIjoiU3ZlbkltaG9seiJ9.veUfaT5sOL7j1yeuSx4fz-XCuPxDZbuajkub5uIzSgQ
@playerId=00000000-0000-0000-0000-000000000000

### Create new game

POST {{host}}/api/players/{{playerId}}/games
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### Get games
GET {{host}}/api/players/{{playerId}}/games
Authorization: Bearer {{token}}
