@host= https://localhost:7052

### Good request
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Sven",
  "lastName": "Imholz",
  "email": "svenimholz@icloud.com",
  "password": "Test1234!"
}

### Bad request | Multple validation errors
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Sven",
  "lastName": "Imholz",
  "email": "svenimholzicloud.com",
  "password": "Tes12"
}

### Bad request | Single validation error
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Sven",
  "lastName": "Imholz",
  "email": "svenimholz@icloud.com",
  "password": "Tes12"
}
